### ISSUE TITLE
Assembly version is 0.0.0.0

### ISSUE THREAD

**Issue by atifaziz** [docopt/docopt.net#122]
Install [dotnet-script](https://www.nuget.org/packages/dotnet-script):

    dotnet tool install --global dotnet-script --version 1.2.1

Run `dotnet script` and type the following lines on each prompt:

    #r "nuget: docopt.net, 0.6.1.11"
    using DocoptNet;
    typeof(Docopt).Assembly

The last line prints:

    [DocoptNet, Version=0.0.0.0, Culture=neutral, PublicKeyToken=7a38c71da49a547e]

Here is how the complete session should look like:

    ❯ dotnet script
    > #r "nuget: docopt.net, 0.6.1.11"
    > using DocoptNet;
    > typeof(Docopt).Assembly
    [DocoptNet, Version=0.0.0.0, Culture=neutral, PublicKeyToken=7a38c71da49a547e]

Note that the assembly version is 0.0.0.0. 

@voieducode, was this intentional (to avoid strong naming issues?) or a slip?

**Comment by voieducode** [comment]
It was not intentional.
