### ISSUE TITLE
How to create optional arguments?

### ISSUE THREAD

**Issue by jtu100** [docopt/docopt.net#14]
I seem unable to create optional arguments. Many examples on the net show things such as:

    my_app [OPTIONAL]

But when I do this I get a this code generated:

    public string ArgOptional { get { return _args["OPTIONAL"].ToString(); } }

So, if I don't pass the OPTIONAL argument, as soon as I try to access it I get an exception due to ToString being called on null. As I want this argument to be optional I expect it to return null or String.Empty not to throw!

**Comment by csMACnz** [comment]
I'm also getting stuck on this issue, maybe it would be better to generate helper methods so we can check for optional options without it crashing, and without having to duplicate the flags.

eg. I'm currently using an added method to my T4 file (which is not ideal)

    public bool IsProvided(string parameter)
    {
        return _args[parameter] != null;
    }

but my code ends up with:

    var outputFile = args.IsProvided("--output") ? args.OptOutput : string.Empty;

it would be nicer to be able to say:

    var outputFile = args.HasOptOutput ? args.OptOutput : string.Empty;


(still would be much nice to just say `var outputFile = args.OptOutput ?? string.Empty;` though)

Does the IsTrue and AsList generated versions have the same NullReferenceException issue?

**Comment by Comandermuffif** [comment]
Should this issue be closed?

**Comment by voieducode** [comment]
yep
