### ISSUE TITLE
Add MatchAsync to `IParser<T>.IResult`

### ISSUE THREAD

**Issue by giggio** [docopt/docopt.net#187]
It is common that the executing code is async, and it is not easily doable with the current API.
We need a `Task`/`ValueTask` returning `Func` for the first argument, so `async`/`await` can be used.

This is my current workaround:

```csharp
ProgramArguments programArguments;
var result = ProgramArguments.CreateParser()
.WithVersion("Naval Fate 2.0")
.Parse(args)
.Match(p => { programArguments = p; return -1; },
    result => { WriteLine(result.Help); return 0; },
    result => { WriteLine(result.Version); return 0; },
    result => { Error.WriteLine(result.Usage); return 1; });
if (result > -1) return result;
// continues with async/await...
return 0;
```

**Comment by atifaziz** [comment]
I'm going to close this as unnecessary, but happy to reconsider if the [presented solutions](https://github.com/docopt/docopt.net/issues/187#issuecomment-1768154217) don't address issue.
