### ISSUE TITLE
T4 macro is broken (0.6.1.6)

### ISSUE THREAD

**Issue by PhilipDaniels** [docopt/docopt.net#19]
Create a brand new console app and create Main.usage.txt as shown in the docs. T4DocoptNet.tt contains this line:

    <#@ assembly name="c:\temp\ConsoleApplication2\packages\docopt.net.0.6.1.6DocoptNet.dll"  #>

which refers to a file that does not exist. I changed it to

    <#@ assembly name="C:\Temp\ConsoleApplication2\packages\docopt.net.0.6.1.6\lib\net40\DocoptNet.dll" #>

which does exist, but still getting 

    ErrorGeneratingOutput

in my T4DocoptNet.cs.

**Comment by voieducode** [comment]
Is there a backslash missing before the dll name?



—

**Comment by PhilipDaniels** [comment]
Well yes...in fact "\lib\net40" is missing as well. The path is simply invalid. But even if you point it to a valid DLL it still gives an error when generating.

**Comment by Spiralis** [comment]
I had the same problem, but fixing the path fixed the compilation error for me.

**Comment by voieducode** [comment]
Got a fix in install.ps1
