### ISSUE TITLE
Better Exception handling

### ISSUE THREAD

**Issue by marcote** [docopt/docopt.net#20]
Hi there

Given this piece of code: 

```
           try
           {
                var docopt = new Docopt();
                var res = docopt.Apply(Usage, args, help: true, exit: true)
           }            
           catch (Exception ex)
           {
                throw new InvalidOperationException("Unable to parse command line arguments", ex);
           }
```

If I give docopt bad arguments, instead of catching the exception, I got : 

```
A first chance exception of type 'DocoptNet.DocoptInputErrorException' occurred in DocoptNet.dll
``` 

Am I doing anything wrong? What would be the correct usage to trap bad arguments ?

Thanks

**Comment by voieducode** [comment]
You are doing nothing wrong, the current error handling and reporting is not great. Do you have any expectations or suggestions on how to trap and process bad arguments?

**Comment by marcote** [comment]
@voieducode I would expect an exception being thrown with a meaningful message. Nothing more. If by any reason I want to ignore the exception, I can catch it and eat it. 
What do you think ?

I will try to see If I can tweak the code to show you a working example.

**Comment by marcote** [comment]
I know what is the problem. The 'bool exit = true' parameter in the Apply method. Changing 'exit = false' shows the behavior I was expecting. 

Thanks!!!
