### ISSUE TITLE
Compilation error: "A namespace cannot directly contain members such as fields or methods"

### ISSUE THREAD

**Issue by AngelEzquerra** [docopt/docopt.net#21]
I just tried to compile the docopt.net example (shown on the readme) using Visual Studio 2013 Community Edition and I got the following compilation error:

"A namespace cannot directly contain members such as fields or methods"

I installed doctopt.net using the builtin Visual Studio package manager. I copied the "NavalFate" example and tried to compile it, getting the error above. This seems similar to issue #4.

**Comment by voieducode** [comment]
Hi

I created a blank project and copied and pasted the Navalfate example but I could not reproduce the problem. There is a problem with the T4 project path though so I'll look at that.

**Comment by voieducode** [comment]
With the last update to support .net core - install.ps1 has trouble generating the right path for a standard console project.

**Comment by voieducode** [comment]
Got a fix in install.ps1
