### ISSUE TITLE
Support dnxcore50 and .NET Core

### ISSUE THREAD

**Issue by giggio** [docopt/docopt.net#22]

**Comment by voieducode** [comment]
Implemented by @jonstoneman

**Comment by jonstoneman** [comment]
When might an updated nuget package be published?

**Comment by voieducode** [comment]
Working on it this weekend - trying to get it to build on my stock dev machine first (no dotnetcore on it).

**Comment by voieducode** [comment]
Also changing appveyor to generate the packages to avoid having to do all this stuff manually...
