### ISSUE TITLE
spaces in filenames

### ISSUE THREAD

**Issue by craiginscotland** [docopt/docopt.net#41]
It does not appear to like args with spaces in them.  Which makes file paths on windows difficult.

Here is a snippet for my USAGE

prog PREPARE (--folderpath=<path> | --azure --jobid=<jobid> --simrun=<simrun> --host=<host> --token=<token>

I have also tried --folderpath<SPACE>path

Both with = and <space> work, when the path has no spaces.  They both fail when I add spaces.

Add a space to the below example and it will fail to parse

.NET string snippet @"prepare --folderpath=""c:\thisthat"" "

**Comment by craiginscotland** [comment]
Actually, here is full snippet.

This will throw exception.  Trying --folderpath=<path> will fail too (instead of space>

const string USAGE2 = @"prog.

            Usage: prog PREPARE --folderpath <path>";

            var opt2 = new Docopt().Apply(USAGE2, @"prepare --folderpath ""c:\this that"" ");

**Comment by craiginscotland** [comment]
Looked into this further.  The string[] version works, it's the string version that has this bug.

**Comment by atifaziz** [comment]
Closed via merge of #98 and 79ef49ee61e7765ed0aac7d6f87b31f21fcc25d6.
