### ISSUE TITLE
condition to properly build the project and have it work correctly

### ISSUE THREAD

**Issue by povociancioni** [docopt/docopt.net#46]
As a beginner I'm watching carefully at what exists and is smart using in the field of commandline application. Such is docopt.

The documentation of the docopt.net naval_fate application is certainly a very complete one, but it still leaves me asking to myself what is the very first step when creating a new file to work with.

I suppose the answer is somehow obvious for many people but still (believe me ), it isn't for me.

I need help.

Thanks a lot.

**Comment by voieducode** [comment]
I agree that the first run experience could be better. Also the error handling could be improved. I do not have a lot of bandwidth to look into this but I am happy to support you if you want to make some improvements.

**Comment by povociancioni** [comment]
Look.! When I wanted to manually copy the code from Program.cs, I saw an unmatched message showing me that there was a ] or perhaps [ that should not. Then I naively thought I could remove "|" (OR, isn't it?) from "--moored --drifting".  Then I had a message that there was a ) or perhaps (  that  unmatched at its turn. Does it help?

**Comment by voieducode** [comment]
Yes i sounds like you tried to address the problem yourself. I have copied
and pasted the code from the sample and it worked for me out of the box. I
do not have time to look into this before this weekend, so stay tuned.

**Comment by atifaziz** [comment]
> Also the error handling could be improved.

Could you expand on what improvements you are thinking about?

**Comment by voieducode** [comment]
> Could you expand on what improvements you are thinking about?

At the moment we just show the usage string if the command line is wrong - there could be some more helpful additional messages to produce such as "Option x requires an operand". I am thinking of following [getopt](https://pubs.opengroup.org/onlinepubs/9699919799/functions/getopt.html)'s error messages and also take inspiration from the [Utility Conventions](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html).

**Comment by voieducode** [comment]
To clarify further on the above, I mean that this behaviour would be the default one and this can be made overridable by client who want more control.

**Comment by povociancioni** [comment]
Hello,

I think that I perfectly understand what I put in my Following first proposition .

You Need to know what the consumer think of the work you’ve been doing. This could help a lot to improving the systems.

I am afraid on the contrary that I was unable to understand the basic functions.

Thanks a lot.

Ciancioni Patrick

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Dinh Doan Van ***@***.***>
Envoyé le :samedi 3 avril 2021 12:25
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [docopt/docopt.net] condition to properly build the project and have it work correctly (#46)


To clarify further on the above, I mean that this behaviour would be the default one and this can be made overridable by client who want more control.

**Comment by atifaziz** [comment]
[Getting up and started has been simplified with a template](https://docopt.github.io/docopt.net/dev/#usage). What's more, designing and testing the usage in your program's help has been made super easy and which you can do [online](https://docopt.github.io/docopt.net/try/) without a project or even downloading docopt.net, so I am going to close this as addressed.
