### ISSUE TITLE
T4 template doesn't run in "T4DocoptNetHostApp"

### ISSUE THREAD

**Issue by atifaziz** [docopt/docopt.net#75]
When running the custom tool from within VS, it fails with the following error:

    Compiling transformation: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

on line 62 of `T4DocoptNet.tt`:

https://github.com/docopt/docopt.net/blob/2ac84371d949b3b98444817b9580e3ff72e2b45a/src/T4DocoptNetHostApp/T4DocoptNet.tt#L62

It looks like I broke something with PR #59 in spite of testing on my end. 😞

The error message makes sense and while it looks like [other people are running into a similar using libraries targeting .NET Standard in T4](https://github.com/dotnet/standard/issues/1669), I don't see a good solution yet. Even if we manage to find a workaround, I think the following line is going to be troublesome:

https://github.com/docopt/docopt.net/blob/2ac84371d949b3b98444817b9580e3ff72e2b45a/src/T4DocoptNetHostApp/T4DocoptNet.tt#L20

It means, targets will have to be added and maintained across all supported runtimes, including .NET Framework, .NET Core and .NET 5+, which seems too burdensome.

One option to explore would be to use [mono/t4](https://github.com/mono/t4) that's now available as a tool. The integration with VS may not be as sweet though but that could be worked around with some sort of a watcher tool.

**Comment by voieducode** [comment]
I have tried adding `<#@ assembly name="NetStandard" #>` and it seems to fix it at least for .NET Standard

**Comment by voieducode** [comment]
I have initially tried to mitigate the problem by having the path correctly set in the NuGet [install.ps1](https://github.com/docopt/docopt.net/blob/7a74df322fd718e2c802ba953855bc6fd016a018/src/NuGet/install.ps1) script. The approach is brittle, but it provides some mitigation for the fresh package installs.

**Comment by atifaziz** [comment]
> I have tried adding `<#@ assembly name="NetStandard" #>` and it seems to fix it at least for .NET Standard

I wonder though how that'll sit with a non-SDK-style project that targets .NET Framework.

I do find what's being attempted with T4 is somewhat split & partial given that some code generation happens in the library:

https://github.com/docopt/docopt.net/blob/7a74df322fd718e2c802ba953855bc6fd016a018/src/DocoptNet/Pattern.cs#L16-L19

Perhaps it's time to look for a fresh approach to the problem? Perhaps something that's done via an MSBuild task? I don't have any proposal off the top of my head at the moment.

**Comment by voieducode** [comment]
Yes I agree. I am a bit disconnect from the .net world. How popular is T4 nowadays?

**Comment by atifaziz** [comment]
> How popular is T4 nowadays?

Can't speak for everyone, but I think it's fine if used in a limited way that's not connected to the IDE and works cross-platform via [mono/t4](https://github.com/mono/t4). I think what people love about T4 is the quick inner dev loop with saving and seeing the generated code/text update almost immediately. I wish `dotnet watch` could make up for that, but I think it's [somewhat limited to web development scenarios for now](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-5.0). I don't have the cycles to explore the options with MS Build because I'd rather channel my energies on exploring the source generator method in PR #77. If I get lightbulb moment for T4 part or a replacement, I'll drop a PR (no promises).

**Comment by voieducode** [comment]
Yes I would rather invest in the source code generator as well.

**Comment by atifaziz** [comment]
Closing since T4 support was removed in PR #136.
